### ISSUE TITLE
Python bindings not working

### ISSUE THREAD

**Issue by luator** [clearpathrobotics/occupancy_grid_utils#18]
Hello,

I am unable to use the Python bindings of this package.
After compilation (using `catkin build`), I can `import occupancy_grid_utils` but it has no members.
When I cd into the src directory and run `python python_test.py` I get the following error:

```
Traceback (most recent call last):
  File "python_test.py", line 5, in <module>
    import occupancy_grid_utils_python as gu
  File "/home/fwidmaier/ws/src/occupancy_grid_utils/src/occupancy_grid_utils_python/__init__.py", line 10, in <module>
    from .str import *
  File "/home/fwidmaier/ws/src/occupancy_grid_utils/src/occupancy_grid_utils_python/str.py", line 56, in <module>
    Cell.__str__ = cell_str
NameError: name 'Cell' is not defined
```

Edit: Forgot to mention that I am using ROS Kinetic on Ubuntu 16.04 (in case it matters)

**Comment by sabrinamoh1** [comment]
Hi, 
Did you close this issue? What was your solution? I am experiencing a similar problem.

**Comment by luator** [comment]
To be honest, I don't remember anymore...  But I assume if I had found a solution back then, I would have posted it here, so probably I didn't find one.
